### ISSUE TITLE
Advanced drawing tools breaks canvas rendering

### ISSUE THREAD

**Issue by TerrorJacktyl** [kakaroto/fvtt-module-furnace#110]
# Bug: advanced drawing tools breaks canvas rendering

## Steps to reproduce

1. Launch a world and a scene on foundry.
2. Ensure 'The Furnace' module and its 'Advanced drawing tools' option in settings is enabled.
3. Draw on the canvas.

### Expected behaviour

The canvas renders the drawings and continues to function as normal.

### Actual behaviour

The canvas stops rendering various elements/layers: sometimes the tokens, grid or everything except the background color (including the scene background image) disappear.

### Client

Machine: Macbook Pro M1 (ARM)
Browser: Firefox 89.0.2 (64-bit)

### Host

Machine: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)

Foundry is running [inside a Docker container](https://github.com/felddy/foundryvtt-docker).

**Comment by kakaroto** [comment]
This module has been abandoned and split into other smaller modules, the drawing tools will never be resurrected unfortunately. You mention the machine and browser, and foundry running in an container, but not the Foundry version. If you're on Foundry 0.8.x, then you should update the module which will bring its new dependencies with it. If you're on 0.7.x, and it's breaking, then disable the module or disable the drawing tools.
See the README file for more information.
