### ISSUE TITLE
Critical Totals are not colored

### ISSUE THREAD

**Issue by apoapostolov** [kakaroto/fvtt-module-furnace#37]
Furnace 1.4.1, Foundry 0.53, Advanced Macros turned on. 

When anyone uses [[dice]] from monster attacks to roll, critical totals are not colored in red or green. They will become colored on Foundry reload.

**Comment by kakaroto** [comment]
The ability to roll dice with `[[formula]]` is not a Furnace feature, but is a native Foundry feature (called 'inline rolls').
I just tested, and I get the same behavior with and without furnace, so (as expected), Furnace is not affecting it.
