### ISSUE TITLE
Drawing tools: allow grid snap to be circumvented

### ISSUE THREAD

**Issue by TheGiddyLimit** [kakaroto/fvtt-module-furnace#39]
I thought this already existed, but maybe I was mistaken; no combination of CTRL/SHIFT/ALT I use seems to disable snapping.

As per title, some hotkey that could be held to disable grid snap (especially with the freehand tool, where only the initial point seems to snap) would be appreciated.

**Comment by kakaroto** [comment]
Thanks. the snap to grid is forcibly done by the parent class now. I disabled it, so it's back to the original behavior. Shift prevents the snap to grid now, as it should.
