### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by 54XR04** [kakaroto/fvtt-module-furnace#56]
When I add text with this module it comes out blurry and faded (even though I have Opacity set to 100%)
![image](https://user-images.githubusercontent.com/67714949/86296384-a981db80-bbc6-11ea-91ce-751339db9163.png)

**Comment by kakaroto** [comment]
What's the font size you used ? Can you screenshot the entire configuration dialog ?

**Comment by 54XR04** [comment]
Here's the full screenshot. 
![image](https://user-images.githubusercontent.com/67714949/86300336-86f4c000-bbd0-11ea-9417-57e4a6a6678e.png)

**Comment by kakaroto** [comment]
Like I said, font size is 10, which is extremely small. so it's written in a very small font and then it's stretched to fit the size of the drawing. I recommend at least a font size of 40.
You can right click on the drawing to bring up the controls and there's a "resize drawing to fit text" button you can try to see what font size of 10 pixels actually looks like when it's not stretched.

**Comment by 54XR04** [comment]
Thanks! Nailed it.
