### ISSUE TITLE
Macro editor is unusable when Macro Marker is enabled

### ISSUE THREAD

**Issue by janssen-io** [kakaroto/fvtt-module-furnace#59]
![example](https://user-images.githubusercontent.com/33344942/87401114-05326880-c5ba-11ea-99bf-6f32dc8681e4.png)

It would be good to discuss what changes we should make to either/both modules to get this fixed.

I also logged this issue on Macro Marker
https://github.com/janssen-io/foundry-macro-marker/issues/4

**Comment by janssen-io** [comment]
I think I might have a fix on my side. Will keep you posted. :)

**Comment by janssen-io** [comment]
Will be fixed in next release of Macro Marker.

**Comment by kakaroto** [comment]
Oups!
Thanks for fixing it. What was the fix? Anything I can improve from my side to avoid other incompatibilities ?

**Comment by janssen-io** [comment]
Not much, I just wrap all children of the form into a new element. I was doing it in such a way that the whole layout got messed up. I think the new one stays closer to the original structure. :)
