### ISSUE TITLE
Superfluous Underlines between Condition Icons in Combat Tracker

### ISSUE THREAD

**Issue by trfunk** [kakaroto/fvtt-module-furnace#66]
**Describe the bug**
If an actor has already taken their turn in a round the system adds additional superfluous underlines between condition icons.

**To reproduce**
1. Add a few tokens to the combat tracker
2. Add conditions to an actor
3. Let actor take their turn

**Expected behavior**
No underlines

**Screenshots**

![image](https://user-images.githubusercontent.com/4313364/96272665-b5a37480-0fce-11eb-8c4d-bfbaa0173208.png)
![image](https://user-images.githubusercontent.com/4313364/96272770-d8ce2400-0fce-11eb-9dc8-1317793da599.png)

**Desktop**
 - OS: Win 10 x64
 - Browser Firefox (83.0a1)
 - Foundryvtt 0.6.6 (hosted on linux)
 - Lancer 0.1.10 (system)
- Furnace 2.2 (everything else disabled)

**Comment by kakaroto** [comment]
Furnace doesn't do anything to that, so I don't see how it could be related to Furnace. 
Sounds more like an issue with either the system itself.
