### ISSUE TITLE
Foundry 0.7.4 Multilevel duplication with Furnace

### ISSUE THREAD

**Issue by Webwra** [kakaroto/fvtt-module-furnace#68]
When I tried Multilevel tokens in 0.7.4 I realised that there are two of everything related to Multilevel tokens, as you can see from the pictures, and every option (cloning, teleport, triggers, etc.) is on by default.

It seems to be caused by The Furnace module, but these two worked together with 0.6.6.

Not sure if it needs to be fixed on this side or the Multilevel tokens side, but I will post this to both.

**Comment by kakaroto** [comment]
You forgot to post the screenshots, so I'm not entirely sure what you  are talking about, but I know of a bug that causes custom tabs (from modules) in a drawing's config window to be duplicated because of Furnace. That might be what you're talking about.

**Comment by Webwra** [comment]
Yes, i belive it might be it.
![Duplicated option](https://user-images.githubusercontent.com/38015643/96334546-e2f52e80-1071-11eb-965c-ab584a7a1e3f.JPG)

**Comment by Webwra** [comment]
Also the contents of the duplicated tabs are merged.
![Setup 1](https://user-images.githubusercontent.com/38015643/96334558-03bd8400-1072-11eb-80f7-829a47b712a4.JPG)
![Setup 2](https://user-images.githubusercontent.com/38015643/96334559-04eeb100-1072-11eb-9ad3-aa501bbeb3bb.JPG)
![Setup 3](https://user-images.githubusercontent.com/38015643/96334560-061fde00-1072-11eb-8b6d-a2ca5185d14a.JPG)

**Comment by kakaroto** [comment]
Yeah, that's the same issue as #62 
thanks
