### ISSUE TITLE
Token Vision option not working with Furnace activated.

### ISSUE THREAD

**Issue by JLtheking2** [kakaroto/fvtt-module-furnace#81]
Core has an option in the token options' vision tab to toggle whether or not a token has vision when you select the token. With furnace active, that option no longer works, and you can no longer see any token's vision.

Is there a way to get this to work? Or is there a GM-specific thing that Furnace implements? There is no option for this in the Furnace configuration menu.

**Comment by kakaroto** [comment]
Just tested, nothing is broken. My guess is that you enabled the "Ignore Token Vision" option for GMs and didn't realize it : 
![image](https://user-images.githubusercontent.com/27990/97680711-84668200-1a6d-11eb-94f5-6e32175370b9.png)
