### ISSUE TITLE
Call macro inside script macros

### ISSUE THREAD

**Issue by Thedvdias** [kakaroto/fvtt-module-furnace#82]
I'm using midiQOL wich lets me call a macro when an item is rolled. The macro is called with a structure in args[0], I want to call another macro but passing some values of args[0]. As far as I understood I can only recursively call a macro through the chat? How can I do it through a script macro ? Thank you.

**Comment by kakaroto** [comment]
Simply like this should work : 
`game.macros.getName("macroName").execute(arg1, arg2, etc...);`
